apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scaling-demo
    argocd.argoproj.io/instance: demo-app
  name: demo
  namespace: scaling-demo
spec:
  replicas: 30
  selector:
    matchLabels:
      app: scaling-demo
  template:
    metadata:
      labels:
        app: scaling-demo
    spec:
      containers:
        - image: 'thorstenhans/aks-scaling-demo:0.0.1'
          livenessProbe:
            httpGet:
              path: /status/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 1
          name: aks-auto-scaler-demo
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /status/ready
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 64Mi
